wallet:
  public_key: AKb6B2s59CSyig1UmuR5xWxVEwK1aRADHMkwkfgFgNby
  nonce: 3
tx_pool:
  threads: 2
  address: tcp://127.0.0.1:10001
validator:
  threads: 2
  address: tcp://127.0.0.1:10002
  consensus: pow
metronome:
  threads: 2
  address: tcp://127.0.0.1:10003
blockchain:
  threads: 2
  address: tcp://127.0.0.1:10004