wallet:
  public_key: AKb6B2s59CSyig1UmuR5xWxVEwK1aRADHMkwkfgFgNby
  nonce: 33
tx_pool:
  threads: 2
  address: tcp://127.0.0.1:10001
validator:
  threads: 2
  address: tcp://127.0.0.1:10002
  memory: 1Gb
  consensus: pom
  fingerprint: Y2Bcjs9U69yZAKGwQnnKEs
metronome:
  threads: 2
  address: tcp://127.0.0.1:10003
blockchain:
  threads: 2
  address: tcp://127.0.0.1:10004